(function (root, factory) {
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = factory();
  } else {
    root.RememberUI = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  function bind(doc) {
    const d = doc || (typeof document !== 'undefined' ? document : null);
    if (!d) return {};

    return {
      gridEl: d.getElementById('grid'),
      movesEl: d.getElementById('moves'),
      timeEl: d.getElementById('time'),
      bestEl: d.getElementById('best'),
      difficultyEl: d.getElementById('difficulty'),
      newGameBtn: d.getElementById('newGameBtn'),
      winModal: d.getElementById('winModal'),
      winStatsEl: d.getElementById('winStats'),
      playAgainBtn: d.getElementById('playAgain'),
      closeModalBtn: d.getElementById('closeModal'),
      ratingStarsEl: d.getElementById('ratingStars'),
      comboToastEl: d.getElementById('comboToast'),
      loseModal: d.getElementById('loseModal'),
      failRetryBtn: d.getElementById('failRetry'),
      failCloseBtn: d.getElementById('failClose'),
      pauseBtn: d.getElementById('pauseBtn'),
      hintBtn: d.getElementById('hintBtn'),
      hintLeftEl: d.getElementById('hintLeft'),
      settingsBtn: d.getElementById('settingsBtn'),
      pauseOverlay: d.getElementById('pauseOverlay'),
      resumeBtn: d.getElementById('resumeBtn'),
      settingsModal: d.getElementById('settingsModal'),
      settingSound: d.getElementById('settingSound'),
      settingVibrate: d.getElementById('settingVibrate'),
      settingPreview: d.getElementById('settingPreview'),
      settingAccent: d.getElementById('settingAccent'),
      settingCardFace: d.getElementById('settingCardFace'),
      settingTheme: d.getElementById('settingTheme'),
      settingMotion: d.getElementById('settingMotion'),
      settingVolume: d.getElementById('settingVolume'),
      settingVolumeValue: d.getElementById('settingVolumeValue'),
      settingSoundPack: d.getElementById('settingSoundPack'),
      settingLanguage: d.getElementById('settingLanguage'),
      settingAdaptive: d.getElementById('settingAdaptive'),
      settingSpaced: d.getElementById('settingSpaced'),
      settingGameMode: d.getElementById('settingGameMode'),
      settingCountdownEasy: d.getElementById('settingCountdownEasy'),
      settingCountdownMedium: d.getElementById('settingCountdownMedium'),
      settingCountdownHard: d.getElementById('settingCountdownHard'),
      countdownConfigEl: d.getElementById('countdownConfig'),
      settingsCancel: d.getElementById('settingsCancel'),
      settingsSave: d.getElementById('settingsSave'),
      shareBtn: d.getElementById('shareBtn'),
      leaderboardList: d.getElementById('leaderboardList'),
      pairsLeftEl: d.getElementById('pairsLeft'),
      progressBarEl: d.getElementById('progressBar'),
      confettiCanvas: d.getElementById('confettiCanvas'),
      dailyModal: d.getElementById('dailyModal'),
      dailyBtn: d.getElementById('dailyBtn'),
      dailyCloseBtn: d.getElementById('dailyClose'),
      dailyStartBtn: d.getElementById('dailyStart'),
      dailyInfoEl: d.getElementById('dailyInfo'),
      achievementsModal: d.getElementById('achievementsModal'),
      achievementsBtn: d.getElementById('achievementsBtn'),
      achievementsClose: d.getElementById('achievementsClose'),
      achievementsList: d.getElementById('achievementsList'),
      achievementsNew: d.getElementById('achievementsNew'),
      exportBtn: d.getElementById('exportBtn'),
      importBtn: d.getElementById('importBtn'),
      importFile: d.getElementById('importFile'),
      toastEl: d.getElementById('toast'),
      statsModal: d.getElementById('statsModal'),
      statsBtn: d.getElementById('statsBtn'),
      statsClose: d.getElementById('statsClose'),
      statsListEl: d.getElementById('statsList'),
      resetDataBtn: d.getElementById('resetData'),
      recallModal: d.getElementById('recallModal'),
      recallChoicesEl: d.getElementById('recallChoices'),
      recallSkipBtn: d.getElementById('recallSkip'),
      recallSubmitBtn: d.getElementById('recallSubmit'),
      nbackBtn: d.getElementById('nbackBtn'),
      nbackModal: d.getElementById('nbackModal'),
      nbackStimEl: d.getElementById('nbackStim'),
      nbackNSelect: d.getElementById('nbackNSelect'),
      nbackSpeedSelect: d.getElementById('nbackSpeedSelect'),
      nbackLenSelect: d.getElementById('nbackLenSelect'),
      nbackStartBtn: d.getElementById('nbackStart'),
      nbackCloseBtn: d.getElementById('nbackClose'),
      guideBtn: d.getElementById('guideBtn'),
      guideModal: d.getElementById('guideModal'),
      guideCloseBtn: d.getElementById('guideClose'),
      guideNoShow: d.getElementById('guideNoShow'),
      guideBasicsList: d.getElementById('guideBasicsList'),
      guideAdvancedList: d.getElementById('guideAdvancedList'),
      guideShortcutsList: d.getElementById('guideShortcutsList'),
      guideNoShowLabel: d.getElementById('guideNoShowLabel'),
      guideOpenHintEl: d.getElementById('guideOpenHint'),
    };
  }

  return {
    bind,
  };
});
